// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnAH4sY-foMHCqpKSiOoAmARpmAw7Atqw',
    appId: '1:695631937426:web:b579b0c128a7a1117a8b4b',
    messagingSenderId: '695631937426',
    projectId: 'firstapplication-68bf18df',
    authDomain: 'firstapplication-68bf18df.firebaseapp.com',
    storageBucket: 'firstapplication-68bf18df.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmzaSqyDzwVa8o7eawNo_ItAD23Hl-R5Y',
    appId: '1:695631937426:android:bc506ce4dbcc48507a8b4b',
    messagingSenderId: '695631937426',
    projectId: 'firstapplication-68bf18df',
    storageBucket: 'firstapplication-68bf18df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaSqjCfmLtkRDPTO2vSvJwczMopywWE40',
    appId: '1:695631937426:ios:5c0cd76012c11e957a8b4b',
    messagingSenderId: '695631937426',
    projectId: 'firstapplication-68bf18df',
    storageBucket: 'firstapplication-68bf18df.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationBatuhangozuyukari',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaSqjCfmLtkRDPTO2vSvJwczMopywWE40',
    appId: '1:695631937426:ios:5c0cd76012c11e957a8b4b',
    messagingSenderId: '695631937426',
    projectId: 'firstapplication-68bf18df',
    storageBucket: 'firstapplication-68bf18df.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationBatuhangozuyukari',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnAH4sY-foMHCqpKSiOoAmARpmAw7Atqw',
    appId: '1:695631937426:web:5a6ee4b3a60ed32e7a8b4b',
    messagingSenderId: '695631937426',
    projectId: 'firstapplication-68bf18df',
    authDomain: 'firstapplication-68bf18df.firebaseapp.com',
    storageBucket: 'firstapplication-68bf18df.firebasestorage.app',
  );
}
